// frameworks/vue/src/components/main/tools/designer/FontFamily.vue
<script>
    export default {
        name: 'FontFamily',
        components: {},
        props: {},
        computed: {
            font() {
                return this.$store.getters['fonts/getFontForCurrentBox'];
            },
            title() {
                return this.font ? this.font.title : '-';
            }
        },
        methods: {}
    }
</script>


<template>
    <div class="FontFamily">
        {{title}}
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .FontFamily {
        background: $theme-color;
        height: 24px;
        padding: 0 8px;
        display: flex;
        align-items: center;
        color: #fff;
        margin-bottom: $grid-size-x2;
        font-weight: 700;
        flex-grow: 1;
    }
</style>

// frameworks/svelte/src/components/tools/designer/FontFamily.svelte
<script>
    import {getCurrentFont, fonts, currentBox_id} from "store/index.js";
    import { updatePropertyOfItem } from 'store/store-tools.js';

    $: {
        let font = $getCurrentFont;
        if (font && !font.loaded && window.WebFont) {
            $fonts = updatePropertyOfItem($fonts, font, 'loaded', true);
            window.WebFont.load({
                google : {
                    families : [font.title + ":" + font.weight]
                },
                loading : function() {},
                active : function(response) {

                },
                inactive : function() {}
            });
        }
    }

</script>


<div class="FontFamily">
    {$getCurrentFont ? $getCurrentFont.title : '-'}
</div>


<style type="text/scss">
    .FontFamily {
        background: #e6be00;
        height: 24px;
        padding: 0 8px;
        display: flex;
        align-items: center;
        color: #fff;
        margin-bottom: 12px;
        font-weight: 700;
        flex-grow: 1;
    }
</style>
