// fontapp/src/components/tools/filter/FontCategory.svelte
<script>
    import { currentCategory } from 'store/index.js'
    let categories;

    categories = [
        'Sans Serif',
        'Serif',
        'Slab Serif',
        'Monospace',
        'Script',
        'Fun'
    ];


    const update = (value) => {
        currentCategory.update(v => value)
    };
</script>


<div class="FontCategory">
    <select
        on:change="{(e) => update(e.target.value)}">
        {#each categories as category}
            <option value={category}>
                {category}
            </option>
        {/each}
    </select>

</div>


<style>
    .FontCategory {

    }
</style>

// frameworks/react/src/components/main/tools/filter/font-category/FontCategory.js
import './FontCategory.scss';
import {updateProperty, updateBox} from "store/actions";
import {getCurrentCategory, getBestMatch} from 'store/selectors';
import { useSelector, useDispatch } from "react-redux";
// import Select from '@material-ui/core/Select';

const FontCategory = () => {
    const dispatch = useDispatch();

    const categories = [
        'Sans Serif',
        'Serif',
        'Slab Serif',
        'Monospace',
        'Script',
        'Fun'
    ];

    const currentCategory = useSelector(state => getCurrentCategory(state));

    const bestMatch = useSelector(state => getBestMatch(state));
    const currentBoxId = useSelector(state => state.boxes.current_id);

    const update = (value) => {
        dispatch(updateProperty({key: 'category', value}));
        dispatch(updateBox({id: currentBoxId, property: 'font_id', value: bestMatch.id}));
    };

    return (
        <div className="FontCategory">
            <select
                value={currentCategory}
                onChange={(e) => {
                    update(e.target.value)
                }}>
                {categories.map(category =>
                    <option
                        key={category}
                        value={category}>{category}</option>
                )}
            </select>
        </div>
    )
};

export default FontCategory;
