// frameworks/vue/src/components/main/tools/parameters/ParameterToggle.vue
<script>
    import Parameter from "../../../../../../../shared/classes/Parameter";

    export default {
        name: 'ParameterToggle',
        components: {},
        props: {
            parameter: {
                type: Parameter,
                required: true
            }
        },
        computed: {},
        methods: {
            toggle(){
                this.$store.commit('parameters/updatePropertyOfItem', {item: this.parameter, property: 'active', value: !this.parameter.active});
            }
        }
    }
</script>


<template>
    <div
        @click="toggle()"
        class="ParameterToggle"></div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .ParameterToggle {
        width: 6px;
        height: 6px;
        border: 2px solid #000;
        background: #fff;
        cursor: pointer;
    }

    .Parameter--inactive {

        .ParameterToggle {
            background: #000;
        }
    }
</style>

// frameworks/svelte/src/components/tools/parameters/ParameterToggle.svelte
<script>
    import {parameters} from 'store/index.js'
    import { updatePropertyOfItem } from 'store/store-tools.js';

    export let parameter;

    const update = () => {
        $parameters = updatePropertyOfItem($parameters, parameter, 'active', !parameter.active);
    }
</script>


<div
    on:click={update}
    class="ParameterToggle">

</div>


<style type="text/scss">
    .ParameterToggle {
        width: 6px;
        height: 6px;
        border: 2px solid #000;
        background: #fff;
        cursor: pointer;
    }

    :global(.Parameter--inactive) {

        .ParameterToggle {
            background: #000;
        }
    }
</style>
