// frameworks/react/src/components/main/tools/administration/search/Search.js
import './Search.scss';
import SearchResults from "./SearchResults";
import {useDispatch, useSelector} from "react-redux";
import {getAllFonts} from "store/selectors";
import {setFontSearch} from "store/actions"

const Search = () => {
    const dispatch = useDispatch();

    const fonts = useSelector(state => getAllFonts(state));
    const search = useSelector(state => state.fonts.search);

    const setSearch = (value) => {
        dispatch(setFontSearch(value));
    };

    const getFonts = () => {
        return fonts.filter(font => {
            return font.title.toLowerCase().indexOf(search.toLowerCase()) > -1;
        })
    };

    const showSearchResults = () => {
        return search.length > 0;
    };



    return (
        <div className="Search tool-box">
            <input
                placeholder="Search font..."
                onChange={e => setSearch(e.target.value)}
                value={search}/>
            {showSearchResults() > 0 ? <SearchResults fonts={getFonts()}/> : null }
        </div>
    );
};

export default Search;

// frameworks/vue/src/components/main/tools/search/Search.vue
<script>
    import SearchResults from "./SearchResults";
    export default {
        name: 'Search',
        components: {SearchResults},
        props: {},
        computed: {
            search: {
                get() {
                    return this.$store.state.search;
                },
                set(value) {
                    this.$store.commit('updateProperty', {key: 'search', value});
                }
            },
            results(){
                if (this.search === '') {
                    return [];
                } else {
                    return this.$store.state.fonts.all.filter(font => {
                        return font.title.toLowerCase().indexOf(this.search.toLowerCase()) > -1;
                    })
                }
            }
        },
        methods: {}
    }
</script>


<template>
    <div class="Search tool-box">
        <div class="Search__container">
            <input
                v-model="search"
                placeholder="Search..."/>
            <SearchResults
                    v-if="results.length > 0"
                    :results="results"/>
        </div>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Search {

        .Search__container {
            position: relative;

            input {
                padding: 4px;
                width: 100%;
                height: 28px;
                outline: none;
            }
        }
    }
</style>
