// frameworks/svelte/src/components/tools/search/SearchResult.svelte
<script>
    import {currentBox_id, boxes, search} from 'store/index.js';
    import { updatePropertyOfItem } from 'store/store-tools.js';

    export let font;

    const select = () => {
        let box = $boxes.find(box => box.id === $currentBox_id);
        $boxes = updatePropertyOfItem($boxes, box, 'font_id', font.id);
        search.set('');
    }
</script>


<div
    on:click={select}
    class="SearchResult">
    {font.title} ({font.weight}) ({font.style})
</div>


<style type="text/scss">
    .SearchResult {
        cursor: pointer;
        padding: 8px 12px;
        border-bottom: 1px solid #ddd;

        &:last-child {
            border-bottom: 0;
        }

        &:hover {
            background: #ddd;
        }
    }
</style>

// frameworks/vue/src/components/main/tools/search/SearchResult.vue
<script>
    import Font from "../../../../../../../shared/classes/Font";

    export default {
        name: 'SearchResult',
        components: {},
        props: {
            font: {
                type: Font,
                required: true
            }
        },
        computed: {
            currentBox(){
                return this.$store.state.boxes.current;
            }
        },
        methods: {
            select() {
                this.$store.commit('boxes/updatePropertyOfItem', {item: this.currentBox, property: 'font_id', value: this.font.id});
                this.$store.commit('updateProperty', {key: 'search', value: ''});
            }
        }
    }
</script>


<template>
    <div
        @click="select()"
        class="SearchResult">
        {{font.title}} ({{font.weight}}) ({{font.style}})
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .SearchResult {
        cursor: pointer;
        padding: 8px 12px;
        border-bottom: 1px solid #ddd;

        &:last-child {
            border-bottom: 0;
        }

        &:hover {
            background: #ddd;
        }
    }
</style>
