// frameworks/vue/src/components/main/tools/designer/FontSize.vue
<script>
    import VueSlider from 'vue-slider-component'

    export default {
        name: 'FontSize',
        components: {
            VueSlider
        },
        props: {},
        computed: {
            currentBox(){
                return this.$store.state.boxes.current;
            },
            fontSize: {
                get() {
                    return this.currentBox ? this.currentBox.fontSize : 50;
                },
                set(value) {
                    this.$store.commit('boxes/updatePropertyOfItem', {item: this.currentBox, property: 'fontSize', value});
                }
            }
        },
        methods: {}
    }
</script>


<template>
    <div class="FontSize designer__row">
        <div class="designer__label">
            Font size
        </div>
        <div class="designer__content">
            <vue-slider
                v-model="fontSize"/>
        </div>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .FontSize {

    }
</style>

// frameworks/react/src/components/main/tools/designer/font-size/FontSize.js
import './FontSize.scss';
import Slider from "@material-ui/core/Slider";
import { getCurrentBox} from "store/selectors";
import {updateBox} from 'store/actions'
import { useSelector, useDispatch } from "react-redux";


const FontSize = () => {
    const dispatch = useDispatch();

    const currentBox = useSelector(state => getCurrentBox(state));

    const update = (value) =>{
        dispatch(updateBox({id: currentBox.id, property: 'fontSize', value}));
    };

    const fontSize = currentBox ? currentBox.fontSize : 50;

    return (
        <div className="FontSize designer__row">
            <div className="designer__label">
                Font size
            </div>
            <div className="designer__content">
                <Slider
                    value={fontSize}
                    onChange={(event, value) => {
                        update(value)
                    }}
                    aria-labelledby="continuous-slider" />
            </div>
        </div>
    )
};

export default FontSize;
