// frameworks/react/src/components/main/tools/administration/favorites/Favorites.js
import './Favorites.scss';
import Favorite from './Favorite';
import {useSelector} from "react-redux";


const Favorites = () => {
    const favorites = useSelector(state => state.favorites.all);

    return (
        <div className="Favorites tool-box">
            <div className="tool-box__title">
                Favorites
            </div>
            <div className="Favorites__list">
                {favorites.map(favorite =>
                    <Favorite
                        key={favorite.id}
                        favorite={favorite}/>
                )}
            </div>

        </div>
    );
};

export default Favorites;

// frameworks/vue/src/components/main/tools/favorites/Favorites.vue
<script>
    import Favorite from "./Favorite";

    export default {
        name: 'Favorites',
        components: {Favorite},
        props: {},
        computed: {
            favorites(){
                return this.$store.state.favorites.all;
            }
        },
        methods: {}
    }
</script>


<template>
    <div class="Favorites tool-box">
        <div class="tool-box__title">
            Favorites
        </div>
        <div class="Favorites__list">
            <Favorite
                v-for="favorite in favorites"
                :favorite="favorite"/>
        </div>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Favorites {

        .Favorites__list {
            display: flex;
            flex-wrap: wrap;
        }
    }
</style>
