// frameworks/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import DATA from "shared/data/index.js";
import {DomSanitizer} from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  cssStyles = null;

  constructor(private sanitizer: DomSanitizer) {
    const getCssVars = (DATA: { [key: string]: any }) => {
      const items: string[] = [];

      const addItems = (keys: { [key: string]: string }) => {
        for (const key in keys) {
          const value: string = keys[key];
          items.push("--" + key + ": " + value);
        }
      }
      addItems(DATA.STYLES.COLORS);
      addItems(DATA.STYLES.SIZES);
      return items.join("; ");
    }

    const css = getCssVars(DATA);
    this.cssStyles = this.sanitizer.bypassSecurityTrustStyle(css);
  }
}

<div class="app" [style]="cssStyles">
  <main-component></main-component>
</div>

// frameworks/vue3/src/App.vue
<script lang="ts">
import {defineComponent} from "vue";
import { useStore } from "vuex";
import DATA from "@/shared/data";

export default defineComponent({
    name: "App",
    setup() {
        const store = useStore();

        const getCssVars = (DATA: { [key: string]: any }) => {
            const items: string[] = [];

            const addItems = (keys: { [key: string]: string }) => {
                for (const key in keys) {
                    const value: string = keys[key];
                    items.push("--" + key + ": " + value);
                }
            }
            addItems(DATA.STYLES.COLORS);
            addItems(DATA.STYLES.SIZES);
            return items.join("; ");
        }
        store.commit("addFonts", DATA.FONTS);


        return {
            cssVars: getCssVars(DATA)
        };
    },
});
</script>

<template>
    <div class="app" :style="cssVars">
        <router-view/>
    </div>
</template>

<style lang="scss">
* {
    box-sizing: border-box;
}

input {
    border :0;
}
</style>
