// fontapp/src/components/tools/parameters/Parameters.svelte
<script>
    import {parameters, currentBox, getCurrentFont} from 'store/index.js'
    import Parameter from "./Parameter.svelte";
    import { updatePropertyOfItem } from 'store/store-tools.js';

    // probably not the best way to create a watch on $currentBox
    let lastBoxId = null;
    $: {
        if ($currentBox) {
            if ($currentBox.id !== lastBoxId) {
                updateParameters();
                lastBoxId = $currentBox.id;
            }

        } else {
            unsetParameters();
        }
    }

    function updateParameters() {
        for (let parameter of $parameters) {
            let value = $getCurrentFont[parameter.key];
            $parameters = updatePropertyOfItem($parameters, parameter, 'value', value);
        }
    }

    function unsetParameters() {
        for (let parameter of $parameters) {
            $parameters = updatePropertyOfItem($parameters, parameter, 'value', 50);
        }
    }
</script>


<div class="Parameters tool-box">
    {#each $parameters as parameter}
        <Parameter parameter={parameter}/>
    {/each}
</div>


<style>
    .Parameters {

    }
</style>

// frameworks/vue/src/components/main/tools/parameters/Parameters.vue
<script>
    import Parameter from "./Parameter";
    export default {
        name: 'Parameters',
        components: {Parameter},
        props: {},
        computed: {
            parameters() {
                return this.$store.state.parameters.all;
            },
            currentBox(){
                return this.$store.state.boxes.current;
            },
            font() {
                return this.$store.getters['fonts/getFontForCurrentBox'];
            }
        },
        methods: {
            updateParameters() {
                for (let parameter of this.parameters) {
                    let value;
                    if (this.currentBox) {
                        value = this.font[parameter.key];
                    } else {
                        value = 50;
                    }
                    this.$store.commit('parameters/updatePropertyOfItem', {item: parameter, property: 'value', value});
                }
            }
        },
        watch: {
            currentBox() {
                this.updateParameters();
            }
        }
    }
</script>


<template>
    <div class="Parameters tool-box">
        <Parameter
            v-for="parameter in parameters"
            :parameter="parameter"/>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Parameters {

    }
</style>
