// frameworks/vue/src/components/main/tools/designer/Designer.vue
<script>
    import FontFamily from "./FontFamily";
    import FavoriteButton from "./FavoriteButton";
    export default {
        name: 'Designer',
        components: {
            FavoriteButton,
            FontFamily
        },
        props: {},
        computed: {},
        methods: {}
    }
</script>


<template>
    <div class="Designer tool-box">
        <div class="tool-box__row">
            <FontFamily/>
            <FavoriteButton/>
        </div>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Designer {

    }
</style>

// frameworks/react/src/components/main/tools/designer/Designer.js
import './Designer.scss';
import Align from "./align/Align";
import FontSize from "./font-size/FontSize";
import FontFamily from "./font-family/FontFamily";
import Color from "./color/Color";
import FavoriteButton from "./FavoriteButton/FavoriteButton";

const Designer = () => {
    return (
        <div className="Designer tool-box">
            <div className="tool-box__row">
                <FontFamily/>
                <FavoriteButton/>
            </div>
            <FontSize/>
            <Color/>
            <Align/>
        </div>
    );
};

export default Designer;
