// fontapp/src/components/desk/box/Text.svelte
<script>
    import {fonts} from 'store/index.js'

    export let box;

    const fontFamily = $fonts.find(font => font.id === box.font_id);

    const getCorrectedFontSize = () => {
        return Math.round(box.fontSize * 400 / fontFamily.relativeFontSize) + 'px';
    };

    const fontFamilyTitle = () => {
        if (fontFamily) {
            return fontFamily.title;
        } else {
            return '';
        }
    };
</script>


<div class="Text">
    <textarea
        style="
            font-size: {getCorrectedFontSize()};
            font-family: {fontFamilyTitle()};
            text-align: {box.textAlign};
            color: {box.color}"
        value={box.string}/>
</div>


<style type="text/scss">
    .Text {
        textarea {
            width: 100%;
            height: 100%;
            border: 0;
            resize: none;
            outline: none;
            vertical-align: baseline;
            background: transparent;
        }
    }
</style>

// react/src/components/main/desk/paper/box/text/Text.js
import './Text.scss';
import {getFontById} from "store/selectors";
import {updateBox} from 'store/actions'
import { useDispatch, useSelector } from "react-redux";

const Text = (props) => {
    const dispatch = useDispatch();

    const margin = 8;
    const fontFamily = useSelector(state => getFontById(state, props.box.font_id));

    const fontFamilyTitle = () => {
        if (fontFamily) {
            return fontFamily.title;
        } else {
            return '';
        }
    };

    const getCorrectedFontSize = () => {
        return Math.round(props.box.fontSize * 400 / fontFamily.relativeFontSize);
    };

    const update = (value) => {
        dispatch(updateBox({id: props.box.id, property: 'string', value}));
    };

    return (
        <div
            style={{
                left: (props.box.left + margin) + 'px',
                top: (props.box.top + margin) + 'px',
                width: (props.box.width - ( 2 * margin)) + 'px',
                height: (props.box.height - ( 2 * margin)) + 'px',
                fontFamily: fontFamilyTitle()

            }}
            className="Text">
                <textarea
                    style={{
                        fontSize: getCorrectedFontSize() + 'px',
                        fontFamily: fontFamilyTitle(),
                        textAlign: props.box.textAlign,
                        color: props.box.color
                    }}
                    value={props.box.string}
                    onChange={(event, value) => {
                        update(event.target.value)
                    }}/>
        </div>
    )
};

export default Text;
