// fontapp/src/components/desk/box/Box.svelte
<script>
    import Text from "./Text.svelte";
    import Handle from "./Handle.svelte";
    import { currentBox_id } from "store/index.js";

    export let box;

    const select = () => {
        currentBox_id.set(box.id);
    }
</script>


<div
    on:click={select}
    class="Box">
    <Text box={box}/>
<!--    <Handle box={box}/>-->
</div>


<style type="text/scss">
    .Box {
        position: relative;
        padding: 8px;
        z-index: 2;

        > .single-resizer {
            border: 1px dotted #e6be00;
            background: transparent;
            z-index: 1;

            .resizable-handler {
                cursor: default!important;
            }

            .square {
                border: 1px solid #e6be00;
            }
        }

        .Text {
            position: absolute;
            z-index: 2;
        }

        .Handle {
            position: absolute;
            z-index: 3;
        }
    }
</style>

// frameworks/vue/src/components/main/desk/box/Box.vue
<script>
    import Box from "./../../../../../../../shared/classes/Box";
    import BoxText from "./Text";

    export default {
        name: 'Box',
        components: {
            BoxText
        },
        props: {
            box: {
                type: Box,
                required: true
            }
        },
        computed: {},
        methods: {
            select() {
                this.$store.commit('boxes/setCurrent', this.box);
            }
        }
    }
</script>


<template>
    <div
        @click="select()"
        class="Box">
        <BoxText :box="box"/>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Box {
        position: relative;
        z-index: 2;

        > .single-resizer {
            border: 1px dotted $theme-color;
            background: #fff;
            z-index: 1;

            .resizable-handler {
                cursor: default!important;
            }

            .square {
                border: 1px solid $theme-color;
            }
        }

        .Text {
            position: absolute;
            z-index: 2;
        }
    }
</style>
