// fontapp/src/components/desk/box/Text.svelte
<script>
    import {fonts} from 'store/index.js'

    export let box, fontFamilyTitle, correctedFontSize;

    $: {
        const getCorrectedFontSize = () => {
            return Math.round(box.fontSize * 400 / getFontFamily().relativeFontSize) + 'px';
        };

        const getFontFamily = () => {
            return $fonts.find(font => font.id === box.font_id);
        };

        const getFontFamilyTitle = () => {
            let fontFamily = $fonts.find(font => font.id === box.font_id);
            if (fontFamily) {
                return fontFamily.title;
            } else {
                return '';
            }
        };

        fontFamilyTitle = getFontFamilyTitle();
        correctedFontSize = getCorrectedFontSize();
    }
</script>


<div class="Text">
    <textarea
        style="
            font-size: {correctedFontSize};
            font-family: {fontFamilyTitle};
            text-align: {box.textAlign};
            color: {box.color}"
        value={box.string}/>
</div>


<style type="text/scss">
    .Text {
        textarea {
            width: 100%;
            height: 100%;
            border: 0;
            resize: none;
            outline: none;
            vertical-align: baseline;
            background: transparent;
        }
    }
</style>

// frameworks/vue/src/components/main/desk/box/Text.vue
<script>
    import Box from "../../../../../../../shared/classes/Box";

    export default {
        name: 'Box-text',
        components: {},
        props: {
            box: {
                type: Box,
                required: true
            }
        },
        computed: {
            font() {
                return this.$store.getters['fonts/getItemById'](this.box.font_id);
            },
            correctedFontSize() {
                return Math.round(this.box.fontSize * 400 / this.font.relativeFontSize);
            }
        },
        methods: {
            loadFont() {
                if (this.font && !this.font.loaded && window.WebFont) {
                    this.$store.commit('fonts/updatePropertyOfItem', {item: this.font, property: 'loaded', value: true});
                    window.WebFont.load({
                        google : {
                            families : [this.font.title + ":" + this.font.weight]
                        },
                        loading : function() {},
                        active : function(response) {

                        },
                        inactive : function() {}
                    });
                }
            }
        },
        watch: {
            font() {
                this.loadFont();
            }
        }
    }
</script>


<template>
    <div class="Text">
        <textarea
            :style="{
                'font-family': font.title,
                'font-size': correctedFontSize + 'px',
                'font-weight': font.weight,
                'text-align': box.textAlign,
                'color': box.color
            }"
            v-model="box.string"/>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Text {
        height: 100%;

        textarea {
            outline: none;
            width: 100%;
            height: 100%;
            resize: none;
            border: 0;
            background: transparent;
        }
    }
</style>
