// frameworks/react/src/components/main/desk/paper/box/text/Text.js
import './Text.scss';
import {getFontById} from "store/selectors";
import {updateBox, setFontLoaded} from 'store/actions'
import { useDispatch, useSelector } from "react-redux";
import {useEffect} from "react";

const Text = (props) => {
    const dispatch = useDispatch();

    const margin = 8;
    const font = useSelector(state => getFontById(state, props.box.font_id));

    const getCorrectedFontSize = () => {
        return Math.round(props.box.fontSize * 400 / font.relativeFontSize);
    };

    const update = (value) => {
        dispatch(updateBox({id: props.box.id, property: 'string', value}));
    };

    useEffect(() => {
        // todo find a way to wait for window.WebFont
        if (font && !font.loaded && window.WebFont) {
            dispatch(setFontLoaded(font));
            window.WebFont.load({
                google : {
                    families : [font.title + ":" + font.weight]
                },
                loading : function() {},
                active : function(response) {

                },
                inactive : function() {}
            });
        }
    });

    return (
        <div
            style={{
                left: (props.box.left + margin) + 'px',
                top: (props.box.top + margin) + 'px',
                width: (props.box.width - ( 2 * margin)) + 'px',
                height: (props.box.height - ( 2 * margin)) + 'px'

            }}
            className="Text">
                <textarea
                    style={{
                        fontSize: getCorrectedFontSize() + 'px',
                        fontFamily: font.title,
                        fontWeight: font.weight,
                        textAlign: props.box.textAlign,
                        color: props.box.color
                    }}
                    value={props.box.string}
                    onChange={(event, value) => {
                        update(event.target.value)
                    }}/>
        </div>
    )
};

export default Text;

// frameworks/vue/src/components/main/desk/box/Text.vue
<script>
    import Box from "../../../../../../../shared/classes/Box";

    export default {
        name: 'Box-text',
        components: {},
        props: {
            box: {
                type: Box,
                required: true
            }
        },
        computed: {
            font() {
                return this.$store.getters['fonts/getItemById'](this.box.font_id);
            },
            correctedFontSize() {
                return Math.round(this.box.fontSize * 400 / this.font.relativeFontSize);
            }
        },
        methods: {
            loadFont() {
                if (this.font && !this.font.loaded && window.WebFont) {
                    this.$store.commit('fonts/updatePropertyOfItem', {item: this.font, property: 'loaded', value: true});
                    window.WebFont.load({
                        google : {
                            families : [this.font.title + ":" + this.font.weight]
                        },
                        loading : function() {},
                        active : function(response) {

                        },
                        inactive : function() {}
                    });
                }
            }
        },
        watch: {
            font() {
                this.loadFont();
            }
        }
    }
</script>


<template>
    <div class="Text">
        <textarea
            :style="{
                'font-family': font.title,
                'font-size': correctedFontSize + 'px',
                'font-weight': font.weight,
                'text-align': box.textAlign,
                'color': box.color
            }"
            v-model="box.string"/>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Text {
        height: 100%;

        textarea {
            outline: none;
            width: 100%;
            height: 100%;
            resize: none;
            border: 0;
            background: transparent;
        }
    }
</style>
