// frameworks/angular/src/app/main/tools/tool-box.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'tool-box',
  template: `
    <div class="tool-box">
      <ng-content></ng-content>
    </div>
  `,
  styles: [
    `
    .tool-box {
      border: 1px dotted rgba(0,0,0,0.4);
      /*padding: var(--GRID_SIZE_X2);*/
      /*margin-bottom: var(--GRID_SIZE_X2);*/
    }
    `
  ],
})
export class ToolBoxComponent {
  name: "Tool-box component"
}

// frameworks/vue3/src/components/main/tools/ToolBox.vue
<script lang="ts">
import {defineComponent} from "vue";

export default defineComponent({
    name: 'ToolBox',
    components: {},
    props: {},
    setup() {
        return {}
    },
});
</script>


<template>
    <div class="ToolBox">
        <slot />
    </div>
</template>


<style lang="scss" scoped>
.ToolBox {
    border: 1px dotted rgba(0,0,0,0.4);
    padding: var(--GRID_SIZE_X2);
    margin-bottom: var(--GRID_SIZE_X2);
}
</style>
