// frameworks/angular/src/app/main/tools/identity/identity.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'identity',
  template: `
    <div class="identity">
      <img src="assets/img/logo_fontapp.jpg" alt="Logo FontApp" />
    </div>
  `,
  styles: [
    `
    .identity {
      height: 60px;
      display: flex;
    }
    `
  ],
})
export class IdentityComponent {
  name: "Identity component"
}

// frameworks/svelte/src/components/tools/Identity.svelte
<script>

</script>


<div class="Identity">
    <img
        class="Identity__logo" src="assets/img/logo_fontapp.jpg"
        alt="Logo FontApp"/>
</div>

<style type="text/scss">
    .Identity {
        height: 60px;
        margin-bottom: 12px;

        img {
            display: block;
            height: 100%;
        }
    }
</style>
