// frameworks/svelte/src/components/tools/search/SearchResults.svelte
<script>
    import SearchResult from "./SearchResult.svelte";
    export let fonts;

</script>


<div class="SearchResults">
    {#each fonts as font}
        <SearchResult
            font={font}/>
    {/each}
</div>


<style type="text/scss">
    .SearchResults {
        height: 200px;
        background: #fff;
        position: absolute;
        top: 28px;
        left: 0;
        width: 100%;
        overflow: auto;
        box-shadow: 2px 2px 8px rgba(0,0,0,0.2);
    }
</style>

// frameworks/vue3/src/components/main/tools/search/SearchResults.vue
<script lang="ts">
import {defineComponent, PropType} from "vue";
import { FONT } from "@/types";
import SearchResult from "@/components/main/tools/search/SearchResult.vue";

export default defineComponent({
    name: 'SearchResults',
    components: {SearchResult},
    props: {
        fonts: {
            type: Array as PropType<FONT[]>
        }
    },
    setup() {
        return {}
    },
});
</script>


<template>
    <div class="SearchResults">
        <SearchResult
            v-for="(font, index) in fonts"
            :key="index"
            :font="font" />
    </div>
</template>


<style lang="scss" scoped>
.SearchResults {
    max-height: 200px;
    background: #fff;
    position: absolute;
    top: 28px;
    left: 0;
    width: 100%;
    overflow: auto;
    box-shadow: 2px 2px 8px rgba(0,0,0,0.2);
}
</style>
