// frameworks/svelte/src/components/tools/search/Search.svelte
<script>
    import SearchResults from "./SearchResults.svelte";
    import {getFontsBySearch, search} from "store/index.js";

</script>


<div class="Search tool-box">
    <input
        placeholder="Search font..."
        bind:value={$search}/>
    {#if $getFontsBySearch.length > 0}
    <SearchResults
        fonts={$getFontsBySearch}/>
    {/if}
</div>


<style type="text/scss">
    .Search {
        position: relative;

        input {
            padding: 4px;
            width: 100%;
            height: 28px;
            outline: none;
        }
    }
</style>

// frameworks/vue3/src/components/main/tools/search/Search.vue
<script lang="ts">
import {defineComponent, computed, ref} from "vue";
import {useStore} from "vuex";
import SearchResults from "@/components/main/tools/search/SearchResults.vue";
import { FONT } from "@/types";

export default defineComponent({
    name: 'Search',
    components: {SearchResults},
    props: {},
    setup() {
        const store = useStore();

        const search = ref(store.state.search);

        return {
            search,
            results: computed(() => store.getters["filtered"]),
            update: () => store.commit("updateSearch", search.value)
        }
    },
});
</script>


<template>
    <div class="Search">
        <input
            v-model="search"
            @keyup="update"
            type="text"
            placeholder="Search..."/>
        <SearchResults
            v-if="results.length > 0"
            :fonts="results"/>
    </div>
</template>


<style lang="scss" scoped>
.Search {
    position: relative;

    input {
        padding: 4px;
        width: 100%;
        height: 28px;
        outline: none;
    }
}
</style>
