// fontapp/src/components/tools/parameters/Parameter.svelte
<script>
    import ParameterSlider from "./ParameterSlider.svelte";
    import ParameterToggle from "./ParameterToggle.svelte";

    export let parameter;
</script>


<div
    class="Parameter"
    class:Parameter--inactive={!parameter.active}>
    <div class="Parameter__title">
        {parameter.title}
    </div>
    <ParameterSlider parameter={parameter}/>
    <ParameterToggle parameter={parameter}/>
</div>


<style type="text/scss">
    .Parameter {
        display: flex;
        align-items: center;
        height: 28px;

        .Parameter__title {
            width: calc(100% - 158px);
        }

        &.Parameter--inactive {
            opacity: 0.5;

            .ParameterSlider {
                pointer-events: none;
            }
        }
    }
</style>

// react/src/components/main/tools/parameters/parameter/Parameter.js
import './Parameter.scss';
import ParameterToggle from "./parameter-toggle/ParameterToggle";
import ParameterSlider from "./parameter-slider/ParameterSlider";

const Parameter = (props) => {

    return (
        <div className={`Parameter ${!props.parameter.active ? 'Parameter--inactive' : '' }`}>
            <div className="Paramater__title">
                {props.parameter.title}
            </div>
            <ParameterSlider
                parameter={props.parameter}/>
            <ParameterToggle
                parameter={props.parameter}/>
        </div>
    );
};

export default Parameter;
