// frameworks/svelte/src/components/tools/designer/Align.svelte
<script>
    import AlignButton from "./AlignButton.svelte";

    const textAligns = ['left', 'center', 'right'];
</script>

<div class="Align designer__row">
    <div class="designer__label">
        Text align
    </div>
    <div class="designer__content">
        <div class="Align__set">
            {#each textAligns as textAlign}
                <AlignButton textAlign={textAlign}/>
            {/each}
        </div>

    </div>
</div>


<style type="text/scss">
    .Align {

        .Align__set {
            display: flex;
        }
    }
</style>

// frameworks/vue/src/components/main/tools/designer/align/Align.vue
<script>
    import AlignButton from "./AlignButton";
    export default {
        name: 'Align',
        components: {AlignButton},
        props: {},
        data() {
            return {
                textAligns: ['left', 'center', 'right']
            }
        },
        computed: {},
        methods: {}
    }
</script>


<template>
    <div class="Align designer__row">
        <div class="designer__label">
            Text align
        </div>
        <div class="designer__content">
            <div class="Align__set">
                <AlignButton
                        v-for="textAlign in textAligns"
                        :textAlign="textAlign"/>
            </div>

        </div>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Align {

        .Align__set {
            display: flex;
        }
    }
</style>
