// frameworks/svelte/src/components/tools/designer/AlignButton.svelte
<script>
    import {currentBox, boxes} from 'store/index.js';
    import {updatePropertyOfItem} from 'store/store-tools.js';
    export let textAlign;

    const update = () => {
        $boxes = updatePropertyOfItem($boxes, $currentBox, 'textAlign', textAlign);
    }
</script>

<div
    on:click={update}
    class="AlignButton"
    class:AlignButton--active={$currentBox !== null && $currentBox.textAlign === textAlign}>
    <img
        src="assets/img/icons/align-{textAlign}.svg"
        alt={textAlign}/>
</div>


<style type="text/scss">
    .AlignButton {
        width: 22px;
        padding: 2px;
        background: #888;
        cursor: pointer;
        margin-right: 6px;

        &.AlignButton--active {
            background: #e6be00;
            pointer-events: none;
        }

        img {
            width: 100%;
            display: block;
        }

        &:hover {
            background: #000;
        }

        &:last-child {
            margin-right: 0;
        }
    }
</style>

// frameworks/vue/src/components/main/tools/designer/align/AlignButton.vue
<script>
    export default {
        name: 'AlignButton',
        components: {},
        props: {
            textAlign: {
                type: String,
                required: true
            }
        },
        computed: {
            currentBox(){
                return this.$store.state.boxes.current;
            },
            isActive() {
                return this.currentBox && this.currentBox.textAlign === this.textAlign;
            }
        },
        methods: {
            select() {
                if (!this.isActive) {
                    this.$store.commit('boxes/updatePropertyOfItem', {item: this.currentBox, property: 'textAlign', value: this.textAlign});
                }
            }
        }
    }
</script>


<template>
    <div
        @click="select()"
        :class="{'AlignButton--active': isActive}"
        class="AlignButton">
        <img :src="'assets/img/tools/align-' + textAlign + '.svg'"/>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .AlignButton {
        width: 24px;
        padding: 2px;
        background: #888;
        cursor: pointer;
        margin-right: 6px;

        &.AlignButton--active {
            background: $theme-color;
            pointer-events: none;
        }

        img {
            width: 100%;
            display: block;
        }

        &:hover {
            background: #000;
        }

        &:last-child {
            margin-right: 0;
        }
    }
</style>
