// frameworks/vue3/src/components/main/tools/Identity.vue
<script lang="ts">
import {defineComponent} from "vue";
import images from "@/shared/images";

export default defineComponent({
    name: 'Identity',
    components: {},
    props: {},
    setup() {
        return {
            image: images.logo
        }
    },
});
</script>

<template>
    <div class="Identity">
        <img :src="image" alt="Logo FontApp" />
    </div>
</template>


<style lang="scss" scoped>
.Identity {
    display: flex;
    height: 60px;
    margin-bottom: var(--GRID_SIZE_X2);

    .Identity__logo {
        height: 100%;
        width: auto;
        display: block;
    }
}
</style>

// frameworks/react/src/components/main/tools/identity/Identity.js
import './Identity.scss';
import images from "shared/images";

const Identity = () => {
    return (
        <div className="Identity">
            <img
                className="Identity__logo" src={images.logo}
                alt="Logo FontApp"/>
        </div>
    );
};

export default Identity;
