// fontapp/src/components/tools/designer/FontFamily.svelte
<script>
    import {getCurrentFont, fonts, currentBox_id} from "store/index.js";
    import { updatePropertyOfItem } from 'store/store-tools.js';

    $: {
        let font = $getCurrentFont;
        if (font && !font.loaded && window.WebFont) {
            $fonts = updatePropertyOfItem($fonts, font, 'loaded', true);
            window.WebFont.load({
                google : {
                    families : [font.title + ":" + font.weight]
                },
                loading : function() {},
                active : function(response) {

                },
                inactive : function() {}
            });
        }
    }

</script>
{$currentBox_id}

<div class="FontFamily">
    {$getCurrentFont ? $getCurrentFont.title : '-'}
</div>


<style type="text/scss">
    .FontFamily {
        background: #e6be00;
        height: 24px;
        padding: 0 8px;
        display: flex;
        align-items: center;
        color: #fff;
        margin-bottom: 12px;
        font-weight: 700;
    }
</style>

// react/src/components/main/tools/designer/font-family/FontFamily.js
import './FontFamily.scss';
import {getCurrentFont} from "store/selectors";
import {setFontLoaded} from "store/actions";
import { useSelector } from "react-redux";
import React, { useEffect } from 'react';
import { useDispatch } from "react-redux";


const FontFamily = () => {
    const dispatch = useDispatch();

    const font = useSelector(state => getCurrentFont(state));

    useEffect(() => {
        // todo find a way to wait for window.WebFont
        if (font && !font.loaded && window.WebFont) {
            dispatch(setFontLoaded(font));
            window.WebFont.load({
                google : {
                    families : [font.title + ":" + font.weight]
                },
                loading : function() {},
                active : function(response) {

                },
                inactive : function() {}
            });
        }
    });

    return (
        <div className="FontFamily">
            {font ? font.title : '-'}
        </div>
    )
};

export default FontFamily;
