// frameworks/react/src/components/main/tools/filter/Filter.js
import './Filter.scss';
import FontCategory from "./font-category/FontCategory";
import FontStyle from "./font-style/FontStyle";
import NumberOfFonts from "./number-of-fonts/NumberOfFonts";

const Filter = () => {
    return (
        <div className="Filter tool-box">
            <FontCategory/>
            {/*<FontStyle/>*/}
            <NumberOfFonts/>
        </div>
    );
};

export default Filter;

// frameworks/vue/src/components/main/tools/filter/Filter.vue
<script>
    import FontCategory from "./FontCategory";
    import NumberOfFonts from "./NumberOfFonts";

    export default {
        name: 'Filter-tool',
        components: {
            NumberOfFonts,
            FontCategory
        },
        props: {},
        computed: {},
        methods: {}
    }
</script>


<template>
    <div class="Filter tool-box">
        <FontCategory/>
        <NumberOfFonts/>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .Filter {

    }
</style>
