// fontapp/src/components/tools/filter/FontCategory.svelte
<script>
    import { currentCategory } from 'store/index.js'
    let categories;

    categories = [
        'Sans Serif',
        'Serif',
        'Slab Serif',
        'Monospace',
        'Script',
        'Fun'
    ];


    const update = (value) => {
        currentCategory.update(v => value)
    };
</script>


<div class="FontCategory">
    <select
        on:change="{(e) => update(e.target.value)}">
        {#each categories as category}
            <option value={category}>
                {category}
            </option>
        {/each}
    </select>

</div>


<style>
    .FontCategory {

    }
</style>

// frameworks/vue/src/components/main/tools/filter/FontCategory.vue
<script>
    export default {
        name: 'FontCategory',
        components: {},
        props: {},
        data(){
            return {
                categories: [
                    'Sans Serif',
                    'Serif',
                    'Slab Serif',
                    'Monospace',
                    'Script',
                    'Fun'
                ]
            }
        },
        computed: {
            currentCategory: {
                get() {
                    return this.$store.state.currentCategory;
                },
                set(value) {
                    this.$store.commit('updateProperty', {key: 'currentCategory', value});
                }
            }
        },
        methods: {},
        mounted(){
            this.$store.commit('updateProperty', {key: 'currentCategory', value: this.categories[0]});
        }
    }
</script>


<template>
    <div class="FontCategory">
        <select
            v-model="currentCategory">
            <option
                v-for="category in categories"
                :value="category">{{category}}</option>
        </select>
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .FontCategory {

    }
</style>
