// frameworks/react/src/components/main/tools/filter/number-of-fonts/NumberOfFonts.js
import './NumberOfFonts.scss';
import React from "react";
import { useSelector } from "react-redux";
import {getFilteredFonts} from "store/selectors";

const NumberOfFonts = () => {
    const n = useSelector(state => getFilteredFonts(state).length);

    return (
        <div className="NumberOfFonts">{n} fonts found</div>
    );
};

export default NumberOfFonts;

// frameworks/vue/src/components/main/tools/filter/NumberOfFonts.vue
<script>
    export default {
        name: 'NumberOfFonts',
        components: {},
        props: {},
        computed: {
            filteredFonts() {
                return this.$store.getters['fonts/getFilteredFonts']
            }
        },
        methods: {}
    }
</script>


<template>
    <div class="NumberOfFonts">
        {{filteredFonts.length}} fonts found
    </div>
</template>


<style lang="scss">
    @import '../../shared/styles/variables.scss';

    .NumberOfFonts {

    }
</style>
